export type BEGIN_AJAX_CALL = 'App/BEGIN_AJAX_CALL'
export const BEGIN_AJAX_CALL: BEGIN_AJAX_CALL = 'App/BEGIN_AJAX_CALL'

export type AJAX_CALL_ERROR = 'App/AJAX_CALL_ERROR'
export const AJAX_CALL_ERROR: AJAX_CALL_ERROR = 'App/AJAX_CALL_ERROR'