export type ENQUEUE_SNACKBAR = 'App/ENQUEUE_SNACKBAR'
export const ENQUEUE_SNACKBAR: ENQUEUE_SNACKBAR = 'App/ENQUEUE_SNACKBAR'

export type REMOVE_SNACKBAR = 'App/REMOVE_SNACKBAR'
export const REMOVE_SNACKBAR: REMOVE_SNACKBAR = 'App/REMOVE_SNACKBAR'